# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Donald Trump', max_length=100)),
                ('email', models.CharField(default='trump@whitehouse.com', max_length=100)),
                ('phone_number', models.CharField(default=123456, max_length=100)),
                ('language', models.CharField(default='spanish', max_length=100)),
                ('mylocation', models.CharField(default=[1, 2, 3, 4, 5, 6, 7, 8], max_length=1000)),
                ('geojson_object', models.TextField()),
            ],
        ),
    ]
